version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: alemeno_db
    restart: always
    environment:
      POSTGRES_USER: alemeno_user
      POSTGRES_PASSWORD: alemeno_password
      POSTGRES_DB: alemeno_transactions
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U alemeno_user -d alemeno_transactions" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: alemeno_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: alemeno_api
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://alemeno_user:alemeno_password@db:5432/alemeno_transactions
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/workspace

  worker:
    build: .
    container_name: alemeno_worker
    restart: always
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1
    environment:
      - DATABASE_URL=postgresql://alemeno_user:alemeno_password@db:5432/alemeno_transactions
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/workspace

volumes:
  pgdata:
